In [1]:
from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import Dataset, random_split, DataLoader
import torch
import torch.nn as nn # layer들을 호출하기 위해서
import numpy as np
import torch.optim as optim # optimization method를 사용하기 위해서
import torch.nn.init as init # weight initialization 해주기 위해서

import torchvision
import matplotlib.pyplot as plt
from torchvision.utils import make_grid
from torchvision.datasets import ImageFolder
import torchvision.transforms as transforms
import torchvision.models as models
from PIL import Image
from collections import OrderedDict

import import_ipynb
from EfficV2_similarity import *
# %matplotlib inline

device = torch.device("cuda:6" if torch.cuda.is_available() else "cpu")

importing Jupyter notebook from EfficV2_similarity.ipynb


In [2]:
model = PretrainedEfficientNet_V2()
model.cpu()

Loaded pretrained weights for efficientnet-b4


PretrainedEfficientNet_V2(
  (network): EfficientNet(
    (_conv_stem): Conv2dStaticSamePadding(
      3, 48, kernel_size=(3, 3), stride=(2, 2), bias=False
      (static_padding): ZeroPad2d((0, 1, 0, 1))
    )
    (_bn0): BatchNorm2d(48, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
    (_blocks): ModuleList(
      (0): MBConvBlock(
        (_depthwise_conv): Conv2dStaticSamePadding(
          48, 48, kernel_size=(3, 3), stride=[1, 1], groups=48, bias=False
          (static_padding): ZeroPad2d((1, 1, 1, 1))
        )
        (_bn1): BatchNorm2d(48, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
        (_se_reduce): Conv2dStaticSamePadding(
          48, 12, kernel_size=(1, 1), stride=(1, 1)
          (static_padding): Identity()
        )
        (_se_expand): Conv2dStaticSamePadding(
          12, 48, kernel_size=(1, 1), stride=(1, 1)
          (static_padding): Identity()
        )
        (_project_conv): Conv2dS

In [3]:
def ImageHandler(user_img_data):
    transform = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.ToTensor()
    ])
    image = transform(user_img_data)

    return image

In [4]:
input1_image = Image.open("../dog_breed/stanford/images/train/n02085620-치와와/n02085620_477.jpg")
input2_image = Image.open("../dog_breed/stanford/images/train/n02085620-치와와/n02085620_477.jpg")

In [5]:
input1 = ImageHandler(input1_image).unsqueeze(0)
input2 = ImageHandler(input2_image).unsqueeze(0)

input1.shape,input2.shape

(torch.Size([1, 3, 256, 256]), torch.Size([1, 3, 256, 256]))

In [6]:
input1.cpu()
input2.cpu()

tensor([[[[0.3333, 0.3333, 0.3490,  ..., 0.3647, 0.3569, 0.3490],
          [0.3294, 0.3373, 0.3725,  ..., 0.3569, 0.3569, 0.3569],
          [0.3333, 0.3412, 0.3804,  ..., 0.3686, 0.3647, 0.3647],
          ...,
          [0.5882, 0.5882, 0.5765,  ..., 0.0078, 0.0078, 0.0157],
          [0.5843, 0.5725, 0.5608,  ..., 0.0078, 0.0118, 0.0235],
          [0.5765, 0.5569, 0.5412,  ..., 0.0196, 0.0196, 0.0314]],

         [[0.2941, 0.2863, 0.2824,  ..., 0.2824, 0.2784, 0.2706],
          [0.2863, 0.2863, 0.2980,  ..., 0.2745, 0.2706, 0.2745],
          [0.2863, 0.2824, 0.3020,  ..., 0.2745, 0.2745, 0.2784],
          ...,
          [0.1529, 0.1608, 0.1608,  ..., 0.0000, 0.0039, 0.0118],
          [0.1451, 0.1412, 0.1412,  ..., 0.0039, 0.0078, 0.0196],
          [0.1333, 0.1216, 0.1137,  ..., 0.0157, 0.0157, 0.0314]],

         [[0.1020, 0.0824, 0.0667,  ..., 0.0863, 0.0824, 0.0745],
          [0.0941, 0.0863, 0.0863,  ..., 0.0784, 0.0745, 0.0824],
          [0.0902, 0.0824, 0.0863,  ..., 0

In [7]:
features1 = model(input1)
features2 = model(input2)

features1, features2

(tensor([[ 2.8679, -0.1118, -0.2514,  ..., -0.2777, -0.1635, -0.2029]],
        grad_fn=<ReshapeAliasBackward0>),
 tensor([[ 2.6857, -0.0846, -0.2294,  ..., -0.2780, -0.1669, -0.1015]],
        grad_fn=<ReshapeAliasBackward0>))

In [8]:
cosine_similarity(features1,features2)

tensor([[0.7283]], grad_fn=<MmBackward0>)